spring.application.name=railway-os
# Server Port - accessible from network
server.port=8080
server.address=0.0.0.0

# MySQL Database Connection
# spring.datasource.url=jdbc:mysql://localhost:3306/railway_db?useSSL=false&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://3BadwDdq5ykn6yK.root:bBy8ae93vCXS1SIb@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/railway_db?sslMode=VERIFY_IDENTITY
spring.datasource.username=3BadwDdq5ykn6yK.root
spring.datasource.password=bBy8ae93vCXS1SIb

# Hibernate Configuration (Auto-creates your tables!)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect